### ISSUE TITLE
Test-Issues-translate-action

### ISSUE THREAD

**Issue by tomsun28** [tomsun28/DockerFile#1]
### 翻译测试  

你好，这里是测试issue comment 翻译功能

很高兴提交这个issue

````
name: 'issue-comment-translator'
on: # only support issue_comment
  issue_comment:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: tomsun28/issues-translate-action@v1
````

**Comment by tomsun28** [comment]
### 翻译测试  

你好，这里是测试issue comment 翻译功能

很高兴提交这个issue

````
name: 'issue-comment-translator'
on: # only support issue_comment
  issue_comment:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: tomsun28/issues-translate-action@v1
````

**Comment by tomsun28** [comment]
### 翻译测试  

你好，这里是测试issue comment 翻译功能

很高兴提交这个issue

````

**Comment by tomsun28** [comment]
### 翻译测试  

你好，这里是测试issue comment 翻译功能

很高兴提交这个issue

````
name: 'issue-comment-translator'
on: # only support issue_comment
  issue_comment:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: tomsun28/issues-translate-action@v1
````
